export enum OnboardingStep {
  MOBILE = "MOBILE",
  MOBILE_OTP = "MOBILE_OTP",
  OUTLET_OWNER = "OUTLET_OWNER",
  OWNER_EMAIL_OTP = "OWNER_EMAIL_OTP",
  TYPE_AND_TIMINGS = "TYPE_AND_TIMINGS",
  IMAGES = "IMAGES",
  DOCUMENTS = "DOCUMENTS",
  REVIEW = "REVIEW",
  COMPLETED = "COMPLETED",
}
